import Head from 'next/head'
import Image from 'next/image'
import About from './components/About'
import Contact from './components/Contact'
import Main from './components/Main'
import Navbar from './components/Navbar'
import Project from './components/Project'
import Projectitem from './components/Projectitem'
import Skills from './components/Skills'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Kylian|Software developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Main />    
< About/>
< Skills/>
<Project/>
{/* <Projectitem /> */}
<Contact/>

</div>
  )
}
